count files in dir recursively: find . -type f | wc -l
working on modifying spender.

need to fix

RuntimeError: The expanded size of the tensor (3921) must match the existing size (4387) at non-singleton dimension 0.  Target sizes: [3921].  Tensor sizes: [4387]

investigate if boss is sufficient or if we need to re-write (look into wavelength range, length, etc.)...is it resampled?